### ISSUE TITLE
cowntdown box の下に編集 box  を置きたい

### ISSUE THREAD

**Issue by koteitan** [koteitan/countdown#2]
@an-apco さん

クエリが何もないアドレスを開いたときに、編集 box が出てきて作れるようにあんずさんの見よう見まねで div を配置してみました。
[https://koteitan.github.io/countdown/](https://koteitan.github.io/countdown/)

なのですが、&lt;br clear="all"&gt; を入れても編集 box が cowntdown box の右に出てきてしまいます
![image](https://github.com/koteitan/countdown/assets/1577128/3e9de9a6-e796-4fe7-b025-a7e620e67072)

本来は
![image](https://github.com/koteitan/countdown/assets/1577128/a12ebc67-1b98-4eaf-9449-517d4001628d)
のように、countdown box の下に編集 box を配置したかったのです。
どうすればいいでしょうか

**Comment by an-apco** [comment]
@koteitan ちょうど今つくってました！！
こんな感じでどうですか？

<img width="1363" alt="Screenshot 2024-04-21 at 23 41 02" src="https://github.com/koteitan/countdown/assets/51256545/fae43015-4338-442c-902a-eb68b2856215">

**Comment by koteitan** [comment]
うおおおおおお!!天才過ぎる～!!!
ありがとうございます!!
何にも文句ないです!!!めっちゃいい!
お願いします～

**Comment by koteitan** [comment]
ちなみに、クレジットですが、
program: koteitan / design: apco
にするのはどうでしょうか

**Comment by an-apco** [comment]
よいです！
その修正も入れておきます！

**Comment by koteitan** [comment]
やったー！ありがとうございます！

**Comment by koteitan** [comment]
デプロイしました
https://koteitan.github.io/countdown/
ありがとうございました!
